inject-method: native
console:
  json-mode: true
display:
  colors: true
  glyphs: true
keys:
  filter:
    - f
    - "/"
  select: ENTER
  ready: CTRL_L
  reinject: CTRL_I
  console: "`"
  delete:
    - KEY_BACKSPACE
    - KEY_DC
  pause: p
  sort-col-next: kRIT3
  sort-col-prev: kLFT3
  sort-normal: kDN3
  sort-reverse: kUP3
  left: KEY_LEFT
  right: KEY_RIGHT
  up: KEY_UP
  down: KEY_DOWN
  hshift-left: kLFT5
  hshift-right: kRIT5
  page-up:
    - KEY_PPAGE
    - CTRL_B
  page-down:
    - KEY_NPAGE
    - CTRL_F
  home: KEY_HOME
  end: KEY_END
  quit: KEY_F(10)
  reload: " "
  reset: CTRL_X
plugins:
  plugin_selector:
    default: true
    shortcut: KEY_F(2)
  script_runner:
    shortcut: KEY_F(3)
    interval: 5
    config:
      script_dir: ~/.pptop/scripts
  vars:
    shortcut: KEY_F(4)
    interval: 0.5
    config:
      list: ~/.pptop/vars.list
  yappi:
    shortcut: KEY_F(5)
    interval: 1
    #filter: lib/python
  help:
    shortcut: KEY_F(1)
  open_files:
    shortcut: KEY_F(6)
    interval: 1
  threads:
    shortcut: KEY_F(7)
    interval: 1
  log:
    shortcut: KEY_F(8)
    interval: 1
    autostart: true
  env:
    shortcut: KEY_F(9)
    interval: 2
  last_exception:
    shortcut: CTRL_E
